// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: Message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // instance id
	Id     []byte `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Sender uint32 `protobuf:"varint,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Data   []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Message) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// provable broadcast
type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value      []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`           // paload
	Validation []byte `protobuf:"bytes,2,opt,name=validation,proto3" json:"validation,omitempty"` // for external validating
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetValidation() []byte {
	if x != nil {
		return x.Validation
	}
	return nil
}

type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sigshare []byte `protobuf:"bytes,1,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{2}
}

func (x *Echo) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

// smvba
type Lock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig   []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *Lock) Reset() {
	*x = Lock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{3}
}

func (x *Lock) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Lock) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Finish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig   []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *Finish) Reset() {
	*x = Finish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Finish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finish) ProtoMessage() {}

func (x *Finish) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finish.ProtoReflect.Descriptor instead.
func (*Finish) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{4}
}

func (x *Finish) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Finish) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Done struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoinShare []byte `protobuf:"bytes,1,opt,name=coinShare,proto3" json:"coinShare,omitempty"`
}

func (x *Done) Reset() {
	*x = Done{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{5}
}

func (x *Done) GetCoinShare() []byte {
	if x != nil {
		return x.CoinShare
	}
	return nil
}

type Halt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig   []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *Halt) Reset() {
	*x = Halt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Halt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Halt) ProtoMessage() {}

func (x *Halt) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Halt.ProtoReflect.Descriptor instead.
func (*Halt) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{6}
}

func (x *Halt) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Halt) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type PreVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vote  bool   `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sig   []byte `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *PreVote) Reset() {
	*x = PreVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreVote) ProtoMessage() {}

func (x *PreVote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreVote.ProtoReflect.Descriptor instead.
func (*PreVote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{7}
}

func (x *PreVote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *PreVote) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PreVote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Vote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vote     bool   `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Value    []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sig      []byte `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	Sigshare []byte `protobuf:"bytes,4,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
}

func (x *Vote) Reset() {
	*x = Vote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{8}
}

func (x *Vote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *Vote) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Vote) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

//apdb
type Store struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vc    string `protobuf:"bytes,1,opt,name=vc,proto3" json:"vc,omitempty"`
	Shard []byte `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	Proof string `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *Store) Reset() {
	*x = Store{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{9}
}

func (x *Store) GetVc() string {
	if x != nil {
		return x.Vc
	}
	return ""
}

func (x *Store) GetShard() []byte {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *Store) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

type Stored struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sigshare []byte `protobuf:"bytes,1,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
}

func (x *Stored) Reset() {
	*x = Stored{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stored) ProtoMessage() {}

func (x *Stored) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stored.ProtoReflect.Descriptor instead.
func (*Stored) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{10}
}

func (x *Stored) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

type Recast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard []byte `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Proof string `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *Recast) Reset() {
	*x = Recast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recast) ProtoMessage() {}

func (x *Recast) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recast.ProtoReflect.Descriptor instead.
func (*Recast) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{11}
}

func (x *Recast) GetShard() []byte {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *Recast) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

//vdd
type Call struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indices []uint32 `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
}

func (x *Call) Reset() {
	*x = Call{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{12}
}

func (x *Call) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

type Strong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardIndices   []uint32 `protobuf:"varint,1,rep,packed,name=shardIndices,proto3" json:"shardIndices,omitempty"`
	SenderShards   [][]byte `protobuf:"bytes,2,rep,name=senderShards,proto3" json:"senderShards,omitempty"`
	ReceiverShards [][]byte `protobuf:"bytes,3,rep,name=receiverShards,proto3" json:"receiverShards,omitempty"`
}

func (x *Strong) Reset() {
	*x = Strong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Strong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strong) ProtoMessage() {}

func (x *Strong) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strong.ProtoReflect.Descriptor instead.
func (*Strong) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{13}
}

func (x *Strong) GetShardIndices() []uint32 {
	if x != nil {
		return x.ShardIndices
	}
	return nil
}

func (x *Strong) GetSenderShards() [][]byte {
	if x != nil {
		return x.SenderShards
	}
	return nil
}

func (x *Strong) GetReceiverShards() [][]byte {
	if x != nil {
		return x.ReceiverShards
	}
	return nil
}

type Weak struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardIndices []uint32 `protobuf:"varint,1,rep,packed,name=shardIndices,proto3" json:"shardIndices,omitempty"`
	SenderShards [][]byte `protobuf:"bytes,2,rep,name=senderShards,proto3" json:"senderShards,omitempty"`
}

func (x *Weak) Reset() {
	*x = Weak{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weak) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weak) ProtoMessage() {}

func (x *Weak) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weak.ProtoReflect.Descriptor instead.
func (*Weak) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{14}
}

func (x *Weak) GetShardIndices() []uint32 {
	if x != nil {
		return x.ShardIndices
	}
	return nil
}

func (x *Weak) GetSenderShards() [][]byte {
	if x != nil {
		return x.SenderShards
	}
	return nil
}

//Dory
type Proposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	View []uint32 `protobuf:"varint,2,rep,packed,name=view,proto3" json:"view,omitempty"`
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{15}
}

func (x *Proposal) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *Proposal) GetView() []uint32 {
	if x != nil {
		return x.View
	}
	return nil
}

type BLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Sig  []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *BLock) Reset() {
	*x = BLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLock) ProtoMessage() {}

func (x *BLock) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLock.ProtoReflect.Descriptor instead.
func (*BLock) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{16}
}

func (x *BLock) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BLock) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type BFinish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig []byte `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *BFinish) Reset() {
	*x = BFinish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BFinish) ProtoMessage() {}

func (x *BFinish) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BFinish.ProtoReflect.Descriptor instead.
func (*BFinish) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{17}
}

func (x *BFinish) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type BLocked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sigshare []byte `protobuf:"bytes,1,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
}

func (x *BLocked) Reset() {
	*x = BLocked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLocked) ProtoMessage() {}

func (x *BLocked) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLocked.ProtoReflect.Descriptor instead.
func (*BLocked) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{18}
}

func (x *BLocked) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

type BLockSetValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid  []uint32 `protobuf:"varint,1,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	Hash [][]byte `protobuf:"bytes,2,rep,name=hash,proto3" json:"hash,omitempty"`
}

func (x *BLockSetValue) Reset() {
	*x = BLockSetValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLockSetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLockSetValue) ProtoMessage() {}

func (x *BLockSetValue) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLockSetValue.ProtoReflect.Descriptor instead.
func (*BLockSetValue) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{19}
}

func (x *BLockSetValue) GetPid() []uint32 {
	if x != nil {
		return x.Pid
	}
	return nil
}

func (x *BLockSetValue) GetHash() [][]byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type BLockSetValidation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig [][]byte `protobuf:"bytes,1,rep,name=sig,proto3" json:"sig,omitempty"`
}

func (x *BLockSetValidation) Reset() {
	*x = BLockSetValidation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLockSetValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLockSetValidation) ProtoMessage() {}

func (x *BLockSetValidation) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLockSetValidation.ProtoReflect.Descriptor instead.
func (*BLockSetValidation) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{20}
}

func (x *BLockSetValidation) GetSig() [][]byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

//wpACSS
type VInShare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S           string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	DskShare    string   `protobuf:"bytes,2,opt,name=dskShare,proto3" json:"dskShare,omitempty"`
	RecPolyEval []string `protobuf:"bytes,3,rep,name=recPolyEval,proto3" json:"recPolyEval,omitempty"`
}

func (x *VInShare) Reset() {
	*x = VInShare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VInShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VInShare) ProtoMessage() {}

func (x *VInShare) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VInShare.ProtoReflect.Descriptor instead.
func (*VInShare) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{21}
}

func (x *VInShare) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *VInShare) GetDskShare() string {
	if x != nil {
		return x.DskShare
	}
	return ""
}

func (x *VInShare) GetRecPolyEval() []string {
	if x != nil {
		return x.RecPolyEval
	}
	return nil
}

type PiVcomMerkle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      [][]byte `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Indicator []int64  `protobuf:"varint,2,rep,packed,name=indicator,proto3" json:"indicator,omitempty"`
}

func (x *PiVcomMerkle) Reset() {
	*x = PiVcomMerkle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PiVcomMerkle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiVcomMerkle) ProtoMessage() {}

func (x *PiVcomMerkle) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiVcomMerkle.ProtoReflect.Descriptor instead.
func (*PiVcomMerkle) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{22}
}

func (x *PiVcomMerkle) GetPath() [][]byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PiVcomMerkle) GetIndicator() []int64 {
	if x != nil {
		return x.Indicator
	}
	return nil
}

type ProofRec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dpki   []byte   `protobuf:"bytes,1,opt,name=dpki,proto3" json:"dpki,omitempty"`
	PCdsk  []byte   `protobuf:"bytes,2,opt,name=PCdsk,proto3" json:"PCdsk,omitempty"`
	VCdpk  string   `protobuf:"bytes,3,opt,name=VCdpk,proto3" json:"VCdpk,omitempty"`
	Wdski  []byte   `protobuf:"bytes,4,opt,name=wdski,proto3" json:"wdski,omitempty"`
	PiDpki string   `protobuf:"bytes,5,opt,name=piDpki,proto3" json:"piDpki,omitempty"`
	PCphi  [][]byte `protobuf:"bytes,6,rep,name=PCphi,proto3" json:"PCphi,omitempty"`
	Wphi   [][]byte `protobuf:"bytes,7,rep,name=wphi,proto3" json:"wphi,omitempty"`
}

func (x *ProofRec) Reset() {
	*x = ProofRec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProofRec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofRec) ProtoMessage() {}

func (x *ProofRec) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofRec.ProtoReflect.Descriptor instead.
func (*ProofRec) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{23}
}

func (x *ProofRec) GetDpki() []byte {
	if x != nil {
		return x.Dpki
	}
	return nil
}

func (x *ProofRec) GetPCdsk() []byte {
	if x != nil {
		return x.PCdsk
	}
	return nil
}

func (x *ProofRec) GetVCdpk() string {
	if x != nil {
		return x.VCdpk
	}
	return ""
}

func (x *ProofRec) GetWdski() []byte {
	if x != nil {
		return x.Wdski
	}
	return nil
}

func (x *ProofRec) GetPiDpki() string {
	if x != nil {
		return x.PiDpki
	}
	return ""
}

func (x *ProofRec) GetPCphi() [][]byte {
	if x != nil {
		return x.PCphi
	}
	return nil
}

func (x *ProofRec) GetWphi() [][]byte {
	if x != nil {
		return x.Wphi
	}
	return nil
}

type PiInShare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gs       []byte    `protobuf:"bytes,1,opt,name=Gs,proto3" json:"Gs,omitempty"`
	PCvss    []byte    `protobuf:"bytes,2,opt,name=PCvss,proto3" json:"PCvss,omitempty"`
	Wvssi    []byte    `protobuf:"bytes,3,opt,name=wvssi,proto3" json:"wvssi,omitempty"`
	PCz      []byte    `protobuf:"bytes,4,opt,name=PCz,proto3" json:"PCz,omitempty"`
	Wz0      []byte    `protobuf:"bytes,5,opt,name=wz0,proto3" json:"wz0,omitempty"`
	VCvs     string    `protobuf:"bytes,6,opt,name=VCvs,proto3" json:"VCvs,omitempty"`
	PiVs     string    `protobuf:"bytes,7,opt,name=piVs,proto3" json:"piVs,omitempty"`
	ProofRec *ProofRec `protobuf:"bytes,8,opt,name=proofRec,proto3" json:"proofRec,omitempty"`
}

func (x *PiInShare) Reset() {
	*x = PiInShare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PiInShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiInShare) ProtoMessage() {}

func (x *PiInShare) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiInShare.ProtoReflect.Descriptor instead.
func (*PiInShare) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{24}
}

func (x *PiInShare) GetGs() []byte {
	if x != nil {
		return x.Gs
	}
	return nil
}

func (x *PiInShare) GetPCvss() []byte {
	if x != nil {
		return x.PCvss
	}
	return nil
}

func (x *PiInShare) GetWvssi() []byte {
	if x != nil {
		return x.Wvssi
	}
	return nil
}

func (x *PiInShare) GetPCz() []byte {
	if x != nil {
		return x.PCz
	}
	return nil
}

func (x *PiInShare) GetWz0() []byte {
	if x != nil {
		return x.Wz0
	}
	return nil
}

func (x *PiInShare) GetVCvs() string {
	if x != nil {
		return x.VCvs
	}
	return ""
}

func (x *PiInShare) GetPiVs() string {
	if x != nil {
		return x.PiVs
	}
	return ""
}

func (x *PiInShare) GetProofRec() *ProofRec {
	if x != nil {
		return x.ProofRec
	}
	return nil
}

type WpAcssShare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V *VInShare  `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	P *PiInShare `protobuf:"bytes,2,opt,name=p,proto3" json:"p,omitempty"`
}

func (x *WpAcssShare) Reset() {
	*x = WpAcssShare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WpAcssShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WpAcssShare) ProtoMessage() {}

func (x *WpAcssShare) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WpAcssShare.ProtoReflect.Descriptor instead.
func (*WpAcssShare) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{25}
}

func (x *WpAcssShare) GetV() *VInShare {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *WpAcssShare) GetP() *PiInShare {
	if x != nil {
		return x.P
	}
	return nil
}

type WpAcssEcho struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sigshare []byte `protobuf:"bytes,1,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
}

func (x *WpAcssEcho) Reset() {
	*x = WpAcssEcho{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WpAcssEcho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WpAcssEcho) ProtoMessage() {}

func (x *WpAcssEcho) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WpAcssEcho.ProtoReflect.Descriptor instead.
func (*WpAcssEcho) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{26}
}

func (x *WpAcssEcho) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

type WpAcssReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md  []byte `protobuf:"bytes,1,opt,name=md,proto3" json:"md,omitempty"`
	Sig []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *WpAcssReady) Reset() {
	*x = WpAcssReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WpAcssReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WpAcssReady) ProtoMessage() {}

func (x *WpAcssReady) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WpAcssReady.ProtoReflect.Descriptor instead.
func (*WpAcssReady) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{27}
}

func (x *WpAcssReady) GetMd() []byte {
	if x != nil {
		return x.Md
	}
	return nil
}

func (x *WpAcssReady) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type WpAcssFinish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sigshare []byte `protobuf:"bytes,1,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
}

func (x *WpAcssFinish) Reset() {
	*x = WpAcssFinish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WpAcssFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WpAcssFinish) ProtoMessage() {}

func (x *WpAcssFinish) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WpAcssFinish.ProtoReflect.Descriptor instead.
func (*WpAcssFinish) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{28}
}

func (x *WpAcssFinish) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

type WpAcssCallHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caller  uint32   `protobuf:"varint,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Indices []uint32 `protobuf:"varint,2,rep,packed,name=indices,proto3" json:"indices,omitempty"`
}

func (x *WpAcssCallHelp) Reset() {
	*x = WpAcssCallHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WpAcssCallHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WpAcssCallHelp) ProtoMessage() {}

func (x *WpAcssCallHelp) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WpAcssCallHelp.ProtoReflect.Descriptor instead.
func (*WpAcssCallHelp) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{29}
}

func (x *WpAcssCallHelp) GetCaller() uint32 {
	if x != nil {
		return x.Caller
	}
	return 0
}

func (x *WpAcssCallHelp) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

type ProofDPRF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	W     []byte `protobuf:"bytes,1,opt,name=w,proto3" json:"w,omitempty"`
	C     []byte `protobuf:"bytes,2,opt,name=c,proto3" json:"c,omitempty"`
	U     []byte `protobuf:"bytes,3,opt,name=u,proto3" json:"u,omitempty"`
	Dpk   []byte `protobuf:"bytes,4,opt,name=dpk,proto3" json:"dpk,omitempty"`
	PiDpk string `protobuf:"bytes,5,opt,name=piDpk,proto3" json:"piDpk,omitempty"`
}

func (x *ProofDPRF) Reset() {
	*x = ProofDPRF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProofDPRF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofDPRF) ProtoMessage() {}

func (x *ProofDPRF) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofDPRF.ProtoReflect.Descriptor instead.
func (*ProofDPRF) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{30}
}

func (x *ProofDPRF) GetW() []byte {
	if x != nil {
		return x.W
	}
	return nil
}

func (x *ProofDPRF) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *ProofDPRF) GetU() []byte {
	if x != nil {
		return x.U
	}
	return nil
}

func (x *ProofDPRF) GetDpk() []byte {
	if x != nil {
		return x.Dpk
	}
	return nil
}

func (x *ProofDPRF) GetPiDpk() string {
	if x != nil {
		return x.PiDpk
	}
	return ""
}

type ProofHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gs        []byte     `protobuf:"bytes,1,opt,name=Gs,proto3" json:"Gs,omitempty"`
	PCdsk     []byte     `protobuf:"bytes,2,opt,name=PCdsk,proto3" json:"PCdsk,omitempty"`
	PCmask    []byte     `protobuf:"bytes,3,opt,name=PCmask,proto3" json:"PCmask,omitempty"`
	WiMask    []byte     `protobuf:"bytes,4,opt,name=wiMask,proto3" json:"wiMask,omitempty"`
	ProofDPRF *ProofDPRF `protobuf:"bytes,5,opt,name=proofDPRF,proto3" json:"proofDPRF,omitempty"`
}

func (x *ProofHelp) Reset() {
	*x = ProofHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProofHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofHelp) ProtoMessage() {}

func (x *ProofHelp) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofHelp.ProtoReflect.Descriptor instead.
func (*ProofHelp) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{31}
}

func (x *ProofHelp) GetGs() []byte {
	if x != nil {
		return x.Gs
	}
	return nil
}

func (x *ProofHelp) GetPCdsk() []byte {
	if x != nil {
		return x.PCdsk
	}
	return nil
}

func (x *ProofHelp) GetPCmask() []byte {
	if x != nil {
		return x.PCmask
	}
	return nil
}

func (x *ProofHelp) GetWiMask() []byte {
	if x != nil {
		return x.WiMask
	}
	return nil
}

func (x *ProofHelp) GetProofDPRF() *ProofDPRF {
	if x != nil {
		return x.ProofDPRF
	}
	return nil
}

type RecCont struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DealerID     uint32     `protobuf:"varint,1,opt,name=dealerID,proto3" json:"dealerID,omitempty"`
	SMasked      []byte     `protobuf:"bytes,2,opt,name=sMasked,proto3" json:"sMasked,omitempty"`
	DPRFContribF []byte     `protobuf:"bytes,3,opt,name=DPRFContribF,proto3" json:"DPRFContribF,omitempty"`
	PiHelp       *ProofHelp `protobuf:"bytes,4,opt,name=piHelp,proto3" json:"piHelp,omitempty"`
}

func (x *RecCont) Reset() {
	*x = RecCont{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecCont) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecCont) ProtoMessage() {}

func (x *RecCont) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecCont.ProtoReflect.Descriptor instead.
func (*RecCont) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{32}
}

func (x *RecCont) GetDealerID() uint32 {
	if x != nil {
		return x.DealerID
	}
	return 0
}

func (x *RecCont) GetSMasked() []byte {
	if x != nil {
		return x.SMasked
	}
	return nil
}

func (x *RecCont) GetDPRFContribF() []byte {
	if x != nil {
		return x.DPRFContribF
	}
	return nil
}

func (x *RecCont) GetPiHelp() *ProofHelp {
	if x != nil {
		return x.PiHelp
	}
	return nil
}

type WpAcssHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []*RecCont `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
}

func (x *WpAcssHelp) Reset() {
	*x = WpAcssHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WpAcssHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WpAcssHelp) ProtoMessage() {}

func (x *WpAcssHelp) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WpAcssHelp.ProtoReflect.Descriptor instead.
func (*WpAcssHelp) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{33}
}

func (x *WpAcssHelp) GetRes() []*RecCont {
	if x != nil {
		return x.Res
	}
	return nil
}

//Dpss
type DpssCom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cold  []byte `protobuf:"bytes,1,opt,name=Cold,proto3" json:"Cold,omitempty"`
	Gsi   []byte `protobuf:"bytes,2,opt,name=Gsi,proto3" json:"Gsi,omitempty"`
	PiOld string `protobuf:"bytes,3,opt,name=piOld,proto3" json:"piOld,omitempty"`
}

func (x *DpssCom) Reset() {
	*x = DpssCom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DpssCom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpssCom) ProtoMessage() {}

func (x *DpssCom) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpssCom.ProtoReflect.Descriptor instead.
func (*DpssCom) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{34}
}

func (x *DpssCom) GetCold() []byte {
	if x != nil {
		return x.Cold
	}
	return nil
}

func (x *DpssCom) GetGsi() []byte {
	if x != nil {
		return x.Gsi
	}
	return nil
}

func (x *DpssCom) GetPiOld() string {
	if x != nil {
		return x.PiOld
	}
	return ""
}

type DpssProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	M   []byte `protobuf:"bytes,1,opt,name=m,proto3" json:"m,omitempty"`
	Sig []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *DpssProof) Reset() {
	*x = DpssProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DpssProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpssProof) ProtoMessage() {}

func (x *DpssProof) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpssProof.ProtoReflect.Descriptor instead.
func (*DpssProof) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{35}
}

func (x *DpssProof) GetM() []byte {
	if x != nil {
		return x.M
	}
	return nil
}

func (x *DpssProof) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type MvbaTuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Md    []byte `protobuf:"bytes,2,opt,name=md,proto3" json:"md,omitempty"`
	Sig   []byte `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *MvbaTuple) Reset() {
	*x = MvbaTuple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MvbaTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MvbaTuple) ProtoMessage() {}

func (x *MvbaTuple) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MvbaTuple.ProtoReflect.Descriptor instead.
func (*MvbaTuple) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{36}
}

func (x *MvbaTuple) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MvbaTuple) GetMd() []byte {
	if x != nil {
		return x.Md
	}
	return nil
}

func (x *MvbaTuple) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type MvbaIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tuple []*MvbaTuple `protobuf:"bytes,1,rep,name=tuple,proto3" json:"tuple,omitempty"`
}

func (x *MvbaIn) Reset() {
	*x = MvbaIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MvbaIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MvbaIn) ProtoMessage() {}

func (x *MvbaIn) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MvbaIn.ProtoReflect.Descriptor instead.
func (*MvbaIn) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{37}
}

func (x *MvbaIn) GetTuple() []*MvbaTuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

type NewCom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gsi []byte `protobuf:"bytes,1,opt,name=Gsi,proto3" json:"Gsi,omitempty"`
}

func (x *NewCom) Reset() {
	*x = NewCom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCom) ProtoMessage() {}

func (x *NewCom) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCom.ProtoReflect.Descriptor instead.
func (*NewCom) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{38}
}

func (x *NewCom) GetGsi() []byte {
	if x != nil {
		return x.Gsi
	}
	return nil
}

type Err struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err []byte `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Err) Reset() {
	*x = Err{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Err) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err) ProtoMessage() {}

func (x *Err) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Err.ProtoReflect.Descriptor instead.
func (*Err) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{39}
}

func (x *Err) GetErr() []byte {
	if x != nil {
		return x.Err
	}
	return nil
}

type AuxCont struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K      uint32 `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	Gs     []byte `protobuf:"bytes,2,opt,name=Gs,proto3" json:"Gs,omitempty"`
	Cvcom  []byte `protobuf:"bytes,3,opt,name=Cvcom,proto3" json:"Cvcom,omitempty"`
	PiVcom string `protobuf:"bytes,4,opt,name=piVcom,proto3" json:"piVcom,omitempty"`
}

func (x *AuxCont) Reset() {
	*x = AuxCont{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[40]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuxCont) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxCont) ProtoMessage() {}

func (x *AuxCont) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[40]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxCont.ProtoReflect.Descriptor instead.
func (*AuxCont) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{40}
}

func (x *AuxCont) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *AuxCont) GetGs() []byte {
	if x != nil {
		return x.Gs
	}
	return nil
}

func (x *AuxCont) GetCvcom() []byte {
	if x != nil {
		return x.Cvcom
	}
	return nil
}

func (x *AuxCont) GetPiVcom() string {
	if x != nil {
		return x.PiVcom
	}
	return ""
}

type Aux struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cont []*AuxCont `protobuf:"bytes,1,rep,name=cont,proto3" json:"cont,omitempty"`
}

func (x *Aux) Reset() {
	*x = Aux{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[41]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aux) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aux) ProtoMessage() {}

func (x *Aux) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[41]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aux.ProtoReflect.Descriptor instead.
func (*Aux) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{41}
}

func (x *Aux) GetCont() []*AuxCont {
	if x != nil {
		return x.Cont
	}
	return nil
}

//init sharing
type VC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Srs   string `protobuf:"bytes,2,opt,name=srs,proto3" json:"srs,omitempty"`
}

func (x *VC) Reset() {
	*x = VC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[42]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VC) ProtoMessage() {}

func (x *VC) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[42]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VC.ProtoReflect.Descriptor instead.
func (*VC) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{42}
}

func (x *VC) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *VC) GetSrs() string {
	if x != nil {
		return x.Srs
	}
	return ""
}

type InitOld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Share []byte   `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Vcom  [][]byte `protobuf:"bytes,2,rep,name=vcom,proto3" json:"vcom,omitempty"`
	Gs    []byte   `protobuf:"bytes,3,opt,name=Gs,proto3" json:"Gs,omitempty"`
	Vc    *VC      `protobuf:"bytes,4,opt,name=vc,proto3" json:"vc,omitempty"`
}

func (x *InitOld) Reset() {
	*x = InitOld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[43]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitOld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOld) ProtoMessage() {}

func (x *InitOld) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[43]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitOld.ProtoReflect.Descriptor instead.
func (*InitOld) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{43}
}

func (x *InitOld) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *InitOld) GetVcom() [][]byte {
	if x != nil {
		return x.Vcom
	}
	return nil
}

func (x *InitOld) GetGs() []byte {
	if x != nil {
		return x.Gs
	}
	return nil
}

func (x *InitOld) GetVc() *VC {
	if x != nil {
		return x.Vc
	}
	return nil
}

type InitNew struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vc *VC `protobuf:"bytes,1,opt,name=vc,proto3" json:"vc,omitempty"`
}

func (x *InitNew) Reset() {
	*x = InitNew{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[44]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitNew) ProtoMessage() {}

func (x *InitNew) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[44]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitNew.ProtoReflect.Descriptor instead.
func (*InitNew) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{44}
}

func (x *InitNew) GetVc() *VC {
	if x != nil {
		return x.Vc
	}
	return nil
}

var File_Message_proto protoreflect.FileDescriptor

var file_Message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x59, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x04, 0x45, 0x63, 0x68,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x2e, 0x0a,
	0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x30, 0x0a,
	0x06, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22,
	0x24, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x6f, 0x69, 0x6e,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x22, 0x2e, 0x0a, 0x04, 0x48, 0x61, 0x6c, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x45, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x56, 0x6f, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x76, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x5e, 0x0a, 0x04,
	0x56, 0x6f, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x43, 0x0a, 0x05,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x76, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x22, 0x24, 0x0a, 0x06, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73,
	0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x61, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x20, 0x0a,
	0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x22,
	0x78, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x0c, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x22, 0x0a,
	0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x73, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64, 0x73, 0x22, 0x4e, 0x0a, 0x04, 0x57, 0x65, 0x61,
	0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x6e,
	0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64, 0x73, 0x22, 0x2e, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x22, 0x2d, 0x0a, 0x05, 0x42, 0x4c, 0x6f,
	0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x1b, 0x0a, 0x07, 0x42, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x25, 0x0a, 0x07, 0x42, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x35, 0x0a, 0x0d,
	0x42, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x22, 0x26, 0x0a, 0x12, 0x42, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x74, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x56, 0x0a, 0x08, 0x76,
	0x49, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x01, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x73, 0x6b, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x73, 0x6b, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x50, 0x6f, 0x6c, 0x79, 0x45, 0x76, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x50, 0x6f, 0x6c, 0x79, 0x45,
	0x76, 0x61, 0x6c, 0x22, 0x40, 0x0a, 0x0c, 0x50, 0x69, 0x56, 0x63, 0x6f, 0x6d, 0x4d, 0x65, 0x72,
	0x6b, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x64, 0x69, 0x63,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xa2, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52,
	0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x70, 0x6b, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x70, 0x6b, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x43, 0x64, 0x73, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x50, 0x43, 0x64, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x56, 0x43, 0x64, 0x70, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x43, 0x64,
	0x70, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x64, 0x73, 0x6b, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x77, 0x64, 0x73, 0x6b, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x44, 0x70,
	0x6b, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x69, 0x44, 0x70, 0x6b, 0x69,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x43, 0x70, 0x68, 0x69, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x05, 0x50, 0x43, 0x70, 0x68, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x70, 0x68, 0x69, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x77, 0x70, 0x68, 0x69, 0x22, 0xba, 0x01, 0x0a, 0x09, 0x70,
	0x69, 0x49, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x47, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x47, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x43, 0x76, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x50, 0x43, 0x76, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x76, 0x73, 0x73, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x77,
	0x76, 0x73, 0x73, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x43, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x50, 0x43, 0x7a, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x7a, 0x30, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x77, 0x7a, 0x30, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x43, 0x76, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x56, 0x43, 0x76, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x69, 0x56, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x56, 0x73,
	0x12, 0x25, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x63, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x63, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x63, 0x22, 0x40, 0x0a, 0x0b, 0x77, 0x70, 0x41, 0x63, 0x73,
	0x73, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x17, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x76, 0x49, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x01, 0x76, 0x12,
	0x18, 0x0a, 0x01, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x69, 0x49,
	0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x01, 0x70, 0x22, 0x28, 0x0a, 0x0a, 0x77, 0x70, 0x41,
	0x63, 0x73, 0x73, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x22, 0x2f, 0x0a, 0x0b, 0x77, 0x70, 0x41, 0x63, 0x73, 0x73, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x73, 0x69, 0x67, 0x22, 0x2a, 0x0a, 0x0c, 0x77, 0x70, 0x41, 0x63, 0x73, 0x73, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x22, 0x42, 0x0a, 0x0e, 0x77, 0x70, 0x41, 0x63, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x48, 0x65,
	0x6c, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e,
	0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x64,
	0x69, 0x63, 0x65, 0x73, 0x22, 0x5d, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x44, 0x50, 0x52,
	0x46, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x77, 0x12,
	0x0c, 0x0a, 0x01, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a,
	0x01, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x70, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x64, 0x70, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x69, 0x44, 0x70, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x69,
	0x44, 0x70, 0x6b, 0x22, 0x8b, 0x01, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x48, 0x65, 0x6c,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x47, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x47,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x43, 0x64, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x50, 0x43, 0x64, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x43, 0x6d, 0x61, 0x73,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x43, 0x6d, 0x61, 0x73, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x69, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x77, 0x69, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x28, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x44, 0x50, 0x52, 0x46, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x44, 0x50, 0x52, 0x46, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x44, 0x50, 0x52,
	0x46, 0x22, 0x87, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x4d, 0x61,
	0x73, 0x6b, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x4d, 0x61, 0x73,
	0x6b, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x50, 0x52, 0x46, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x69, 0x62, 0x46, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x44, 0x50, 0x52, 0x46, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x46, 0x12, 0x22, 0x0a, 0x06, 0x70, 0x69, 0x48, 0x65, 0x6c,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x48,
	0x65, 0x6c, 0x70, 0x52, 0x06, 0x70, 0x69, 0x48, 0x65, 0x6c, 0x70, 0x22, 0x28, 0x0a, 0x0a, 0x77,
	0x70, 0x41, 0x63, 0x73, 0x73, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x1a, 0x0a, 0x03, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x63, 0x43, 0x6f, 0x6e, 0x74,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x07, 0x44, 0x70, 0x73, 0x73, 0x43, 0x6f, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x43, 0x6f, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x73, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x47, 0x73, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x4f, 0x6c, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x69, 0x4f, 0x6c, 0x64, 0x22, 0x2b, 0x0a, 0x09,
	0x44, 0x70, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x0c, 0x0a, 0x01, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x43, 0x0a, 0x09, 0x4d, 0x76, 0x62,
	0x61, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x0e, 0x0a, 0x02,
	0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x2a,
	0x0a, 0x06, 0x4d, 0x76, 0x62, 0x61, 0x49, 0x6e, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x75, 0x70, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x76, 0x62, 0x61, 0x54, 0x75,
	0x70, 0x6c, 0x65, 0x52, 0x05, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x22, 0x1a, 0x0a, 0x06, 0x4e, 0x65,
	0x77, 0x43, 0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x73, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x47, 0x73, 0x69, 0x22, 0x17, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22,
	0x55, 0x0a, 0x07, 0x41, 0x75, 0x78, 0x43, 0x6f, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x47, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x47, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x76, 0x63, 0x6f,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x43, 0x76, 0x63, 0x6f, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x69, 0x56, 0x63, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x69, 0x56, 0x63, 0x6f, 0x6d, 0x22, 0x23, 0x0a, 0x03, 0x41, 0x75, 0x78, 0x12, 0x1c, 0x0a,
	0x04, 0x63, 0x6f, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x41, 0x75,
	0x78, 0x43, 0x6f, 0x6e, 0x74, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x02, 0x56,
	0x43, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x73, 0x22, 0x58, 0x0a, 0x07, 0x49, 0x6e, 0x69,
	0x74, 0x4f, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x63,
	0x6f, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x76, 0x63, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x47, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x47, 0x73, 0x12, 0x13,
	0x0a, 0x02, 0x76, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x56, 0x43, 0x52,
	0x02, 0x76, 0x63, 0x22, 0x1e, 0x0a, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x4e, 0x65, 0x77, 0x12, 0x13,
	0x0a, 0x02, 0x76, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x56, 0x43, 0x52,
	0x02, 0x76, 0x63, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Message_proto_rawDescOnce sync.Once
	file_Message_proto_rawDescData = file_Message_proto_rawDesc
)

func file_Message_proto_rawDescGZIP() []byte {
	file_Message_proto_rawDescOnce.Do(func() {
		file_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_Message_proto_rawDescData)
	})
	return file_Message_proto_rawDescData
}

var file_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_Message_proto_goTypes = []interface{}{
	(*Message)(nil),            // 0: Message
	(*Value)(nil),              // 1: Value
	(*Echo)(nil),               // 2: Echo
	(*Lock)(nil),               // 3: Lock
	(*Finish)(nil),             // 4: Finish
	(*Done)(nil),               // 5: Done
	(*Halt)(nil),               // 6: Halt
	(*PreVote)(nil),            // 7: PreVote
	(*Vote)(nil),               // 8: Vote
	(*Store)(nil),              // 9: Store
	(*Stored)(nil),             // 10: Stored
	(*Recast)(nil),             // 11: Recast
	(*Call)(nil),               // 12: Call
	(*Strong)(nil),             // 13: Strong
	(*Weak)(nil),               // 14: Weak
	(*Proposal)(nil),           // 15: Proposal
	(*BLock)(nil),              // 16: BLock
	(*BFinish)(nil),            // 17: BFinish
	(*BLocked)(nil),            // 18: BLocked
	(*BLockSetValue)(nil),      // 19: BLockSetValue
	(*BLockSetValidation)(nil), // 20: BLockSetValidation
	(*VInShare)(nil),           // 21: vInShare
	(*PiVcomMerkle)(nil),       // 22: PiVcomMerkle
	(*ProofRec)(nil),           // 23: ProofRec
	(*PiInShare)(nil),          // 24: piInShare
	(*WpAcssShare)(nil),        // 25: wpAcssShare
	(*WpAcssEcho)(nil),         // 26: wpAcssEcho
	(*WpAcssReady)(nil),        // 27: wpAcssReady
	(*WpAcssFinish)(nil),       // 28: wpAcssFinish
	(*WpAcssCallHelp)(nil),     // 29: wpAcssCallHelp
	(*ProofDPRF)(nil),          // 30: proofDPRF
	(*ProofHelp)(nil),          // 31: proofHelp
	(*RecCont)(nil),            // 32: RecCont
	(*WpAcssHelp)(nil),         // 33: wpAcssHelp
	(*DpssCom)(nil),            // 34: DpssCom
	(*DpssProof)(nil),          // 35: DpssProof
	(*MvbaTuple)(nil),          // 36: MvbaTuple
	(*MvbaIn)(nil),             // 37: MvbaIn
	(*NewCom)(nil),             // 38: NewCom
	(*Err)(nil),                // 39: Err
	(*AuxCont)(nil),            // 40: AuxCont
	(*Aux)(nil),                // 41: Aux
	(*VC)(nil),                 // 42: VC
	(*InitOld)(nil),            // 43: InitOld
	(*InitNew)(nil),            // 44: InitNew
}
var file_Message_proto_depIdxs = []int32{
	23, // 0: piInShare.proofRec:type_name -> ProofRec
	21, // 1: wpAcssShare.v:type_name -> vInShare
	24, // 2: wpAcssShare.p:type_name -> piInShare
	30, // 3: proofHelp.proofDPRF:type_name -> proofDPRF
	31, // 4: RecCont.piHelp:type_name -> proofHelp
	32, // 5: wpAcssHelp.res:type_name -> RecCont
	36, // 6: MvbaIn.tuple:type_name -> MvbaTuple
	40, // 7: Aux.cont:type_name -> AuxCont
	42, // 8: InitOld.vc:type_name -> VC
	42, // 9: InitNew.vc:type_name -> VC
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Finish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Done); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Halt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Store); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stored); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Call); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Strong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weak); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BFinish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BLocked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BLockSetValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BLockSetValidation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VInShare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PiVcomMerkle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProofRec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PiInShare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WpAcssShare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WpAcssEcho); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WpAcssReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WpAcssFinish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WpAcssCallHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProofDPRF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProofHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecCont); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WpAcssHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DpssCom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DpssProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MvbaTuple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MvbaIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[39].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Err); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[40].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuxCont); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[41].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aux); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[42].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[43].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitOld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[44].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitNew); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
		MessageInfos:      file_Message_proto_msgTypes,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_rawDesc = nil
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
