syntax = "proto3";

option go_package = "/protobuf";

message Message {
  string type = 1;// instance id
  bytes id = 2;
  uint32 sender = 3;
  bytes data = 4;
}


// provable broadcast
message Value{
  bytes value = 1;// paload
  bytes validation = 2;// for external validating
}
message Echo{
  bytes sigshare = 1 ;
}

// smvba
message Lock{
  bytes value = 1;
  bytes sig = 2;
}
message Finish{
  bytes value = 1;
  bytes sig = 2;
}
message Done{
  bytes coinShare = 1 ;
}
message Halt{//Halt:=<Finish> of the round-leader
  bytes value = 1;
  bytes sig = 2;
}
message PreVote{
  bool vote = 1;
  bytes value = 2;
  bytes sig = 3;
}
message Vote{
  bool vote = 1;
  bytes value =2;
  bytes sig =3;
  bytes sigshare = 4;
}

//apdb
message Store{
  bytes vc = 1;
  bytes shard =2;
  repeated bytes proof1 = 3;
  repeated int64 proof2 = 4;
}
message Stored{
  bytes sigshare = 1 ;
}
message Recast{
  bytes shard = 1;
  repeated bytes proof1 = 2;
  repeated int64 proof2 = 3;
}

//vdd
message Call{
  repeated uint32 indices = 1;
}
message Strong{
  repeated  uint32 shardIndices = 1;
  repeated  bytes senderShards = 2;
  repeated  bytes receiverShards = 3;
}
message Weak{
  repeated  uint32 shardIndices = 1;
  repeated  bytes senderShards = 2;
}


//Dory
message Proposal{
  bytes tx = 1;
  repeated uint32 view = 2;
}

message BLock{
  bytes hash = 1;
  bytes sig = 2;
}
message BFinish{
  bytes sig = 1;
}
message BLocked{
  bytes sigshare = 1;
}

message BLockSetValue{
  repeated uint32 pid = 1;
  repeated bytes hash = 2;
}
message BLockSetValidation{
  repeated bytes sig = 1;
}

//wpACSS
message vInShare{
  bytes s=1;
  bytes dskShare=2;
  repeated bytes recPolyEval = 3;
}

message PiVcomMerkle{
  repeated bytes path = 1;
  repeated int64 indicator = 2;
}

message PiRec{
  bytes Cdk=1;
  bytes wdki=2;
  repeated bytes Crec=3;
  repeated bytes weval=4;
}

message piInShare{
  bytes Gs=1;
  bytes Cvss=2;
  bytes wvssi=3;
  bytes Cz=4;
  bytes wz0 = 5;
  bytes Cvcom=6;
  PiVcomMerkle piVcom=7;
  PiRec piRec=8;
}

message wpAcssShare{
  vInShare v = 1;
  piInShare p = 2;
}

message wpAcssEcho{
  bytes sigshare = 1;
}

message wpAcssCallHelp{
  uint32 caller = 1;
  repeated uint32 indices = 2;
}

message piDPRF{
  bytes w=1;
  bytes c=2;
  bytes u=3;
  bytes dvk=4;
}

message piHelp{
  bytes Gs=1;
  bytes Cdk =2;
  bytes Cmask =3;
  bytes wiMask =4;
  piDPRF piDPRF = 5;
}

message RecCont{
  uint32 dealerID = 1;
  bytes sMasked = 2;
  bytes DPRFContribF = 3;
  piHelp piHelp = 4;
}

message wpAcssHelp{
  repeated RecCont res = 1;
}

//Dpss
message DpssCom{
  bytes Cold = 1;
  bytes Gsi = 2;
  PiVcomMerkle piOld = 3;
}

message DpssProof{
  bytes m = 1;
  bytes sig = 2;
}